apiVersion : apps/v1
kind: Deployment
metadata:
  name: demo-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-2
  template:
    metadata:
      labels:
        app: demo-2
    spec:
      containers:
        - name: demo-2
          image: "registry.hub.docker.com/riko20xx/demo:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 18081
---
apiVersion: v1
kind: Service
metadata:
    name: demo-2
    annotations:
     service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: demo-2

---
